### ISSUE TITLE
Support for additional fields

### ISSUE THREAD

**Issue by aaronjanse** [Fallenstedt/twitter-stream#6]
First, this library is awesome. I spent hours looking for a Twitter v2 Streaming library, and this worked perfectly on my first try.

Twitter supports adding extra fields to streams [by adding parameters to the /2/tweets/search/stream request](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream). It would be cool if there was a way to enable this using this library.

If you're busy, I'd be happy to make a PR to do so. In the meantime, it was easy to modify the library locally to hard-code this functionality :-)

**Comment by Fallenstedt** [comment]
Hi @aaronjanse 

Creating structs for `/2/tweets/search/stream` responses is on my todo-list as a requirement for the v1 release. I have not started this work yet, however, now that I see there is interest in this library, we should prioritize it.

I would love to see your idea! When you create a PR, can you tag me on it? Maybe we can work on this feature together.

**Comment by aaronjanse** [comment]
Sounds good! I'll update to v0.2.0 then start working on a PR :-)

**Comment by Fallenstedt** [comment]
@aaronjanse I took a pass at this and came up with another idea. What do you think about this idea:

Instead of maintaining a struct with all possible fields returned by Twitter, we leave it up the consumer of the library unmarshal the `[]byte` into their struct. The burden of managing all possible return values is greater than the value of creating the `type EveryPossibleFieldFromTwitter struct {...}`

Additionally, more value could be delivered by enabling developers to curate their query params for the `GET v2/tweets/search/streem`. These could be arguments passed into the `StartStream` method. The possible query parameters we can use for this endpoint can be found here: https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/get-tweets-search-stream

I have a work in progress branch here: https://github.com/Fallenstedt/twitter-stream/pull/11

**Comment by aaronjanse** [comment]
I think that's reasonable! As a user, it should be very straightforward to deserialize into custom structs.

I must admit that I've been sidetracked from making a PR, and I probably won't be able to contribute new features within the near future. But I'll upstream as a PR any changes I make locally if I happen to find a bug :-)

Thanks again for your work on this library!

**Comment by Fallenstedt** [comment]
Fixed in: https://github.com/Fallenstedt/twitter-stream/pull/12
Will be available in v0.3.0 soon.
